version: '3'
tasks:
  build:
    desc: Build the Spring Boot application
    cmds:
      - ./mvnw clean package -DskipTests
    sources:
      - "src/**/*.java"
    generates:
      - "target/*.jar"

  start:
    desc: Run the Spring Boot application services individually
    cmds:
      - mvn spring-boot:run
    interactive: false

  stop:
    desc: Stop apps
    cmds:
      - sh kill.ports.sh  8090

  check:
    desc: Check severs
    cmds:
      - curl -i http://127.0.0.1:8090/actuator/health

  serve:
    desc: Run all services using Docker Compose
    cmds:
      - docker compose -f docker/main.yml up -d
    interactive: true

  test:
    desc: Run unit and integration tests
    cmds:
      - mvn test
    sources:
      - "src/**/*.java"
    generates:
      - "target/surefire-reports"

  clean:
    desc: Clean build artifacts
    cmds:
      - ./mvnw clean
    generates:
      - "target/"

  format:
    desc: Format Java code using Spotless
    cmds:
      - ./mvnw spotless:apply
    sources:
      - "src/**/*.java"

  lint:
    desc: Check Java code formatting using Checkstyle
    cmds:
      - ./mvnw checkstyle:check

  dependencies:
    desc: Check for updated project dependencies
    cmds:
      - ./mvnw versions:display-dependency-updates
      - ./mvnw versions:display-plugin-updates

  docker-build:
    desc: Build a Docker image for the application
    cmds:
      - docker build -t pcoundia .
      - docker compose -f docker/main.yml up -d --build
    sources:
      - "Dockerfile"
      - "src/**"
    generates:
      - "target/*.jar"
